# Generated by Django 2.2.9 on 2020-01-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArananKelimeler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelime', models.CharField(max_length=200)),
                ('uygunluk_onayi', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ruyatabirleri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelime', models.CharField(max_length=200)),
                ('tabiri', models.TextField()),
                ('ekleme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('aranma_sayisi', models.IntegerField(null=True)),
            ],
        ),
    ]
