# Generated by Django 2.2.9 on 2020-01-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruyatabirleri', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruyatabirleri',
            name='ekleme_tarihi',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ruyatabirleri',
            name='kelime',
            field=models.TextField(),
        ),
    ]
