# Generated by Django 2.2.9 on 2020-01-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruyatabirleri', '0002_auto_20200109_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruyatabirleri',
            name='ekleme_tarihi',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ruyatabirleri',
            name='kelime',
            field=models.CharField(max_length=200),
        ),
    ]
