# Generated by Django 2.2.9 on 2020-01-14 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruyatabirleri', '0006_ruyatabirleri2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ruyatabirleri1',
        ),
    ]
