# Generated by Django 2.2.9 on 2020-01-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruyatabirleri', '0008_auto_20200115_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruyatabirleri',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
