# Generated by Django 2.2.9 on 2020-01-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruyatabirleri', '0009_auto_20200115_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruyatabirleri1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelime', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('tabiri', models.TextField()),
                ('ekleme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('aranma_sayisi', models.IntegerField(null=True)),
                ('ingilizce_kelime', models.CharField(max_length=200, null=True)),
                ('ingilizce_tabir', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ruyatabirleri',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
