# Generated by Django 2.2.9 on 2020-01-15 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruyatabirleri', '0010_auto_20200115_1438'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ruyatabirleri1',
        ),
    ]
