# Generated by Django 2.2.9 on 2020-01-16 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruyatabirleri', '0011_delete_ruyatabirleri1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruyatabirleri',
            name='kelime',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ruyatabirleri',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
    ]
