# Generated by Django 2.2.9 on 2020-01-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruyatabirleri', '0012_auto_20200117_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruyatabirleri',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
