# Generated by Django 2.2.9 on 2020-01-17 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruyatabirleri', '0013_ruyatabirleri_updated'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ruyatabirleri',
            new_name='Ruyatabirleri1',
        ),
    ]
