# Generated by Django 2.2.9 on 2020-01-17 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruyatabirleri', '0015_ruyatabirleri2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ruyatabirleri1',
        ),
        migrations.DeleteModel(
            name='Ruyatabirleri2',
        ),
    ]
