# Generated by Django 2.2.9 on 2020-01-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruyatabirleri', '0016_auto_20200117_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruyatabirleri2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelime', models.CharField(default='', max_length=255)),
                ('slug', models.SlugField(blank=True, default='', max_length=255)),
                ('tabiri', models.TextField()),
                ('ekleme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('aranma_sayisi', models.IntegerField(null=True)),
                ('ingilizce_kelime', models.CharField(max_length=200, null=True)),
                ('ingilizce_tabir', models.TextField(null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
