# Generated by Django 2.2.9 on 2020-02-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruyatabirleri', '0019_ruyatabirleri'),
    ]

    operations = [
        migrations.CreateModel(
            name='yildizname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=200)),
                ('anne_ismi', models.CharField(max_length=200)),
                ('cinsiyet', models.CharField(choices=[('Cinsiyetinizi Seçiniz', 'Cinsiyetinizi Seçiniz'), ('Erkek', 'Erkek'), ('Kadın', 'Kadın')], default='Cinsiyetinizi Seçiniz', max_length=200)),
            ],
        ),
    ]
