# Generated by Django 2.2.9 on 2020-02-22 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruyatabirleri', '0021_yildizname1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='yildizname',
        ),
    ]
