# Generated by Django 2.2.9 on 2020-02-22 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruyatabirleri', '0022_delete_yildizname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='yildizname1',
            new_name='yildizname',
        ),
    ]
