# Generated by Django 2.2.9 on 2020-02-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruyatabirleri', '0023_auto_20200223_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='iletisim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=200)),
                ('soy_isim', models.CharField(max_length=200)),
                ('eposta', models.EmailField(max_length=200)),
                ('mesaj', models.TextField()),
            ],
        ),
    ]
