# Generated by Django 2.2.9 on 2020-03-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruyatabirleri', '0024_iletisim'),
    ]

    operations = [
        migrations.CreateModel(
            name='KuranBilgi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sure_no', models.IntegerField()),
                ('sure_isim', models.CharField(max_length=200)),
                ('ayet_say', models.IntegerField()),
                ('ayet_no', models.IntegerField()),
                ('ayet', models.TextField()),
                ('ayet_meal', models.TextField()),
            ],
        ),
    ]
