# Generated by Django 2.2.9 on 2020-03-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruyatabirleri', '0025_kuranbilgi'),
    ]

    operations = [
        migrations.CreateModel(
            name='KuranKelime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sure_no', models.IntegerField()),
                ('ayet_no', models.IntegerField()),
                ('keliime_no', models.IntegerField()),
                ('kelime_arapca', models.CharField(max_length=200)),
                ('kelime_turkce', models.CharField(max_length=200)),
            ],
        ),
    ]
