# Generated by Django 2.2.9 on 2020-03-08 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruyatabirleri', '0026_kurankelime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kurankelime',
            old_name='keliime_no',
            new_name='kelime_no',
        ),
    ]
