# Generated by Django 2.2.9 on 2020-07-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruyatabirleri', '0030_auto_20200702_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruyatabirlerix',
            name='kelime_ar2',
            field=models.SlugField(allow_unicode=True, max_length=200, null=True),
        ),
    ]
