# Generated by Django 2.2.9 on 2020-07-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruyatabirleri', '0032_ruyatabirlerix_slug_ru'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruyatabirleri_ru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelime', models.CharField(default='', max_length=255)),
                ('slug', models.SlugField(blank=True, default='', max_length=255)),
                ('tabiri', models.TextField()),
                ('ekleme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('aranma_sayisi', models.IntegerField(null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='ruyatabirlerix',
            name='slug_ru',
            field=models.SlugField(allow_unicode=True, blank=True, default='', max_length=255),
        ),
    ]
