# Generated by Django 2.2.9 on 2020-07-09 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruyatabirleri', '0033_auto_20200709_2328'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ruyatabirleri_ru',
        ),
    ]
