# Generated by Django 2.2.9 on 2020-07-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruyatabirleri', '0034_delete_ruyatabirleri_ru'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruyatabirlerix2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelime_tr', models.CharField(max_length=255)),
                ('slug_tr', models.SlugField(blank=True, max_length=255, unique=True)),
                ('tabir_tr', models.TextField()),
                ('kelime_en', models.CharField(max_length=200)),
                ('tabiri_en', models.TextField()),
                ('altr_en_url', models.URLField(blank=True)),
                ('kelime_es', models.CharField(max_length=200)),
                ('slug_es', models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True)),
                ('tabiri_es', models.TextField()),
                ('altr_es_url', models.URLField(blank=True)),
                ('ekleme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ruyatabirlerix',
            name='kelime_ar2',
        ),
    ]
