# Generated by Django 2.2.9 on 2020-07-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruyatabirleri', '0036_auto_20200711_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ruyatabirlerix2',
            old_name='tabir_tr',
            new_name='tabiri_tr',
        ),
        migrations.AddField(
            model_name='ruyatabirlerix2',
            name='altr_ru_url',
            field=models.URLField(blank=True),
        ),
    ]
