# Generated by Django 2.2.9 on 2020-07-11 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruyatabirleri', '0037_auto_20200711_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruyatabirlerix2',
            name='kelime_ru',
        ),
    ]
