# Generated by Django 2.2.9 on 2020-07-11 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruyatabirleri', '0039_ruyatabirlerix2_kelime_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruyatabirlerix2',
            name='kelime_ru',
        ),
    ]
