# Generated by Django 2.2.9 on 2020-07-11 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruyatabirleri', '0042_auto_20200711_2115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ruyatabirlerix2',
        ),
    ]
