# Generated by Django 2.2.9 on 2020-07-11 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruyatabirleri', '0046_ruyatabirlerix3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ruyatabirlerix3',
        ),
    ]
