# Generated by Django 2.2.9 on 2020-07-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruyatabirleri', '0049_rtxyorum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rtxyorum',
            name='bilinc_alti',
            field=models.CharField(choices=[('e', 'Evet'), ('h', 'Hayır')], help_text='Yatmadan önce veya gün içerisinde gördüğünüz rüya ile ilgili bir olay yaşadınız mı? veya hayal kurdunuz mu?', max_length=1),
        ),
        migrations.AlterField(
            model_name='rtxyorum',
            name='cinsiyet',
            field=models.CharField(choices=[('c', 'Cinsiyetiniz'), ('e', 'Erkek'), ('k', 'Kadın')], help_text='Lütfen Cinsiyetinizi Belirtiniz.', max_length=1),
        ),
        migrations.AlterField(
            model_name='rtxyorum',
            name='eposta',
            field=models.EmailField(help_text='Lütfen Eposta Adresinizi Yazınız.', max_length=200),
        ),
        migrations.AlterField(
            model_name='rtxyorum',
            name='eposta1',
            field=models.EmailField(help_text='Lütfen Eposta Adresinizi Doğrulayınız.', max_length=200),
        ),
        migrations.AlterField(
            model_name='rtxyorum',
            name='isim',
            field=models.CharField(help_text='Lütfen İsminizi Yazınız', max_length=200),
        ),
        migrations.AlterField(
            model_name='rtxyorum',
            name='kayit_tarihi',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rtxyorum',
            name='ruya',
            field=models.TextField(help_text='Lütfen rüyanızı basit cümlelerle ayrıntılı olarak anlatınız. Cümlelerin sonuna nokta işareti koymayı unutmayınızı.'),
        ),
        migrations.AlterField(
            model_name='rtxyorum',
            name='ruya_zamanı',
            field=models.CharField(choices=[('1', 'Gece Yarısında'), ('2', 'Güneş doğmadan hemen önce veya hemen sonra'), ('3', 'Gün içerisinde')], help_text='Lütfen Cinsiyetinizi Belirtiniz.', max_length=1),
        ),
        migrations.AlterField(
            model_name='rtxyorum',
            name='soy_isim',
            field=models.CharField(help_text='Lütfen Soyisminizi Yazınız', max_length=200),
        ),
    ]
