# Generated by Django 2.2.9 on 2020-07-13 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruyatabirleri', '0050_auto_20200713_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rtxyorum',
            name='ruya_zamanı',
        ),
    ]