# Generated by Django 2.2.9 on 2020-07-13 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruyatabirleri', '0053_auto_20200713_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rtxyorum',
            name='kayit_tarihi',
        ),
    ]
