# Generated by Django 2.2.9 on 2020-07-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruyatabirleri', '0054_remove_rtxyorum_kayit_tarihi'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtxyorum',
            name='kayit_tarihi',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
