# Generated by Django 2.2.9 on 2020-07-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruyatabirleri', '0057_rtxyorum_geri_donus'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtxyorum',
            name='ruya_zaman',
            field=models.CharField(help_text='Lütfen rüyayı ne zaman gördüğünüzü belirtiniz.', max_length=200, null=True),
        ),
    ]
