# Generated by Django 2.2.9 on 2020-07-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruyatabirleri', '0059_remove_rtxyorum_ruya_zaman'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtxyorum',
            name='ruya_zamanı',
            field=models.CharField(help_text='Lütfen rüyayı ne zaman gördüğünüzü belirtiniz.', max_length=200, null=True),
        ),
    ]
