# Generated by Django 2.2.9 on 2020-07-15 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruyatabirleri', '0060_rtxyorum_ruya_zamanı'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rtxyorum',
            name='ruya_zamanı',
        ),
    ]

