# Generated by Django 2.2.9 on 2020-07-17 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruyatabirleri', '0061_remove_rtxyorum_ruya_zamanı'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ruyatabirlerix',
        ),
    ]
