# Generated by Django 2.2.9 on 2020-07-17 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruyatabirleri', '0062_delete_ruyatabirlerix'),
    ]

    operations = [
        migrations.DeleteModel(
            name='iletisim',
        ),
    ]
