# Generated by Django 2.2.9 on 2020-07-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruyatabirleri', '0063_delete_iletisim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rtx_iletisim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=200)),
                ('soy_isim', models.CharField(max_length=200)),
                ('eposta', models.EmailField(max_length=200)),
                ('mesaj', models.TextField()),
            ],
        ),
    ]
