# Generated by Django 2.2.9 on 2020-07-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruyatabirleri', '0064_rtx_iletisim'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtxyorum',
            name='cevap',
            field=models.TextField(help_text='Buraya gönderilen rüya yorumları yazılacak', null=True),
        ),
    ]
