# Generated by Django 2.2.9 on 2020-07-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruyatabirleri', '0065_rtxyorum_cevap'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtx_iletisim',
            name='cevap',
            field=models.TextField(help_text='Cevap metni buraya yazılacak', null=True),
        ),
        migrations.AddField(
            model_name='rtx_iletisim',
            name='geri_donus',
            field=models.BooleanField(default=False, help_text='Cevap verilen mesajlar true yapılacak'),
        ),
        migrations.AddField(
            model_name='rtx_iletisim',
            name='kayit_tarihi',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
