# Generated by Django 2.2.9 on 2020-07-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruyatabirleri', '0066_auto_20200721_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtx_iletisim',
            name='eposta1',
            field=models.EmailField(help_text='Lütfen Eposta Adresinizi Doğrulayınız.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rtx_iletisim',
            name='eposta',
            field=models.EmailField(help_text='Lütfen Eposta Adresinizi Yazınız.', max_length=200),
        ),
        migrations.AlterField(
            model_name='rtx_iletisim',
            name='isim',
            field=models.CharField(help_text='Lütfen İsminizi Yazınız', max_length=200),
        ),
        migrations.AlterField(
            model_name='rtx_iletisim',
            name='mesaj',
            field=models.TextField(help_text='Mesajınızı yazınız'),
        ),
        migrations.AlterField(
            model_name='rtx_iletisim',
            name='soy_isim',
            field=models.CharField(help_text='Lütfen Soyisminizi Yazınız', max_length=200),
        ),
    ]
