# Generated by Django 2.2.9 on 2020-08-11 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruyatabirleri', '0070_ruyatabirlerix5'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ruyatabirlerix5',
        ),
    ]
