# Generated by Django 2.2.9 on 2020-08-11 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruyatabirleri', '0072_auto_20200811_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruyatabirlerix3',
            name='altr_ar_url',
        ),
        migrations.RemoveField(
            model_name='ruyatabirlerix3',
            name='altr_ch_url',
        ),
        migrations.RemoveField(
            model_name='ruyatabirlerix3',
            name='kelime_ar',
        ),
        migrations.RemoveField(
            model_name='ruyatabirlerix3',
            name='kelime_ch',
        ),
        migrations.RemoveField(
            model_name='ruyatabirlerix3',
            name='slug_ar',
        ),
        migrations.RemoveField(
            model_name='ruyatabirlerix3',
            name='slug_ch',
        ),
        migrations.RemoveField(
            model_name='ruyatabirlerix3',
            name='tabiri_ar',
        ),
        migrations.RemoveField(
            model_name='ruyatabirlerix3',
            name='tabiri_ch',
        ),
    ]
