# Generated by Django 2.2.9 on 2020-08-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruyatabirleri', '0078_ruyatabirlerix5'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruyatabirlerix5',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
