# Generated by Django 2.2.9 on 2020-08-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruyatabirleri', '0079_ruyatabirlerix5_slug_en'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ruyatabirlerix3',
        ),
        migrations.AlterField(
            model_name='ruyatabirlerix5',
            name='slug_tr',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True),
        ),
    ]
